'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace SysproWCF
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://SYSPROWcfService", ConfigurationName:="SysproWCF.ISYSPROWcfService")>  _
    Public Interface ISYSPROWcfService
        
        <System.ServiceModel.OperationContractAttribute(Action:="GetLogonProfile", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/GetLogonProfileResponse")>  _
        Function GetLogonProfile(ByVal UserId As String) As System.IO.Stream
        
        <System.ServiceModel.OperationContractAttribute(Action:="GetLogonProfile", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/GetLogonProfileResponse")>  _
        Function GetLogonProfileAsync(ByVal UserId As String) As System.Threading.Tasks.Task(Of System.IO.Stream)
        
        <System.ServiceModel.OperationContractAttribute(Action:="Run", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/RunResponse")>  _
        Function Run(ByVal UserId As String, ByVal BusinessObject As String, ByVal Parameter As String) As System.IO.Stream
        
        <System.ServiceModel.OperationContractAttribute(Action:="Run", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/RunResponse")>  _
        Function RunAsync(ByVal UserId As String, ByVal BusinessObject As String, ByVal Parameter As String) As System.Threading.Tasks.Task(Of System.IO.Stream)
        
        <System.ServiceModel.OperationContractAttribute(Action:="QueryQueryW", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/QueryQueryWResponse")>  _
        Function QueryQueryW(ByVal UserId As String, ByVal BusinessObject As String, ByVal XmlIn As String) As Byte()
        
        <System.ServiceModel.OperationContractAttribute(Action:="QueryQueryW", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/QueryQueryWResponse")>  _
        Function QueryQueryWAsync(ByVal UserId As String, ByVal BusinessObject As String, ByVal XmlIn As String) As System.Threading.Tasks.Task(Of Byte())
        
        <System.ServiceModel.OperationContractAttribute(Action:="TransactionPostW", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/TransactionPostWResponse")>  _
        Function TransactionPostW(ByVal UserId As String, ByVal BusinessObject As String, ByVal XmlParameters As String, ByVal XmlIn As String) As Byte()
        
        <System.ServiceModel.OperationContractAttribute(Action:="TransactionPostW", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/TransactionPostWResponse")>  _
        Function TransactionPostWAsync(ByVal UserId As String, ByVal BusinessObject As String, ByVal XmlParameters As String, ByVal XmlIn As String) As System.Threading.Tasks.Task(Of Byte())
        
        <System.ServiceModel.OperationContractAttribute(Action:="GetImage", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/GetImageResponse")>  _
        Function GetImage(ByVal Filename As String) As System.IO.Stream
        
        <System.ServiceModel.OperationContractAttribute(Action:="GetImage", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/GetImageResponse")>  _
        Function GetImageAsync(ByVal Filename As String) As System.Threading.Tasks.Task(Of System.IO.Stream)
        
        <System.ServiceModel.OperationContractAttribute(Action:="GetSystemInformation", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/GetSystemInformationResponse")>  _
        Function GetSystemInformation() As System.IO.Stream
        
        <System.ServiceModel.OperationContractAttribute(Action:="GetSystemInformation", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/GetSystemInformationResponse")>  _
        Function GetSystemInformationAsync() As System.Threading.Tasks.Task(Of System.IO.Stream)
        
        <System.ServiceModel.OperationContractAttribute(Action:="GetVersion", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/GetVersionResponse")>  _
        Function GetVersion() As System.IO.Stream
        
        <System.ServiceModel.OperationContractAttribute(Action:="GetVersion", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/GetVersionResponse")>  _
        Function GetVersionAsync() As System.Threading.Tasks.Task(Of System.IO.Stream)
        
        <System.ServiceModel.OperationContractAttribute(Action:="CallGC", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/CallGCResponse")>  _
        Function CallGC() As System.IO.Stream
        
        <System.ServiceModel.OperationContractAttribute(Action:="CallGC", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/CallGCResponse")>  _
        Function CallGCAsync() As System.Threading.Tasks.Task(Of System.IO.Stream)
        
        <System.ServiceModel.OperationContractAttribute(Action:="Encrypt", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/EncryptResponse")>  _
        Function Encrypt(ByVal InputString As String) As System.IO.Stream
        
        <System.ServiceModel.OperationContractAttribute(Action:="Encrypt", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/EncryptResponse")>  _
        Function EncryptAsync(ByVal InputString As String) As System.Threading.Tasks.Task(Of System.IO.Stream)
        
        <System.ServiceModel.OperationContractAttribute(Action:="GetSYSPROMedia", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/GetSYSPROMediaResponse")>  _
        Function GetSYSPROMedia(ByVal MultimediaFlag As String, ByVal ObjectType As String, ByVal KeyField As String, ByVal EnetGuid As String) As System.IO.Stream
        
        <System.ServiceModel.OperationContractAttribute(Action:="GetSYSPROMedia", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/GetSYSPROMediaResponse")>  _
        Function GetSYSPROMediaAsync(ByVal MultimediaFlag As String, ByVal ObjectType As String, ByVal KeyField As String, ByVal EnetGuid As String) As System.Threading.Tasks.Task(Of System.IO.Stream)
        
        <System.ServiceModel.OperationContractAttribute(Action:="GetSYSPROImageThumbnail", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/GetSYSPROImageThumbnailResponse")>  _
        Function GetSYSPROImageThumbnail(ByVal MultimediaFlag As String, ByVal ObjectType As String, ByVal KeyField As String, ByVal EnetGuid As String, ByVal Width As Integer, ByVal Height As Integer) As System.IO.Stream
        
        <System.ServiceModel.OperationContractAttribute(Action:="GetSYSPROImageThumbnail", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/GetSYSPROImageThumbnailResponse")>  _
        Function GetSYSPROImageThumbnailAsync(ByVal MultimediaFlag As String, ByVal ObjectType As String, ByVal KeyField As String, ByVal EnetGuid As String, ByVal Width As Integer, ByVal Height As Integer) As System.Threading.Tasks.Task(Of System.IO.Stream)
        
        <System.ServiceModel.OperationContractAttribute(Action:="Logon", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/LogonResponse")>  _
        Function Logon(ByVal [Operator] As String, ByVal OperatorPassword As String, ByVal CompanyId As String, ByVal CompanyPassword As String, ByVal LanguageCode As String, ByVal LogLevel As String, ByVal EncoreInstance As String, ByVal XmlIn As String) As System.IO.Stream
        
        <System.ServiceModel.OperationContractAttribute(Action:="Logon", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/LogonResponse")>  _
        Function LogonAsync(ByVal [Operator] As String, ByVal OperatorPassword As String, ByVal CompanyId As String, ByVal CompanyPassword As String, ByVal LanguageCode As String, ByVal LogLevel As String, ByVal EncoreInstance As String, ByVal XmlIn As String) As System.Threading.Tasks.Task(Of System.IO.Stream)
        
        <System.ServiceModel.OperationContractAttribute(Action:="Logoff", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/LogoffResponse")>  _
        Function Logoff(ByVal UserId As String) As System.IO.Stream
        
        <System.ServiceModel.OperationContractAttribute(Action:="Logoff", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/LogoffResponse")>  _
        Function LogoffAsync(ByVal UserId As String) As System.Threading.Tasks.Task(Of System.IO.Stream)
        
        <System.ServiceModel.OperationContractAttribute(Action:="QueryBrowse", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/QueryBrowseResponse")>  _
        Function QueryBrowse(ByVal UserId As String, ByVal XmlIn As String) As System.IO.Stream
        
        <System.ServiceModel.OperationContractAttribute(Action:="QueryBrowse", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/QueryBrowseResponse")>  _
        Function QueryBrowseAsync(ByVal UserId As String, ByVal XmlIn As String) As System.Threading.Tasks.Task(Of System.IO.Stream)
        
        <System.ServiceModel.OperationContractAttribute(Action:="QueryFetch", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/QueryFetchResponse")>  _
        Function QueryFetch(ByVal UserId As String, ByVal XmlIn As String) As System.IO.Stream
        
        <System.ServiceModel.OperationContractAttribute(Action:="QueryFetch", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/QueryFetchResponse")>  _
        Function QueryFetchAsync(ByVal UserId As String, ByVal XmlIn As String) As System.Threading.Tasks.Task(Of System.IO.Stream)
        
        <System.ServiceModel.OperationContractAttribute(Action:="QueryQuery", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/QueryQueryResponse")>  _
        Function QueryQuery(ByVal UserId As String, ByVal BusinessObject As String, ByVal XmlIn As String) As System.IO.Stream
        
        <System.ServiceModel.OperationContractAttribute(Action:="QueryQuery", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/QueryQueryResponse")>  _
        Function QueryQueryAsync(ByVal UserId As String, ByVal BusinessObject As String, ByVal XmlIn As String) As System.Threading.Tasks.Task(Of System.IO.Stream)
        
        <System.ServiceModel.OperationContractAttribute(Action:="NextKey", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/NextKeyResponse")>  _
        Function NextKey(ByVal UserId As String, ByVal XmlIn As String) As System.IO.Stream
        
        <System.ServiceModel.OperationContractAttribute(Action:="NextKey", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/NextKeyResponse")>  _
        Function NextKeyAsync(ByVal UserId As String, ByVal XmlIn As String) As System.Threading.Tasks.Task(Of System.IO.Stream)
        
        <System.ServiceModel.OperationContractAttribute(Action:="PreviousKey", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/PreviousKeyResponse")>  _
        Function PreviousKey(ByVal UserId As String, ByVal XmlIn As String) As System.IO.Stream
        
        <System.ServiceModel.OperationContractAttribute(Action:="PreviousKey", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/PreviousKeyResponse")>  _
        Function PreviousKeyAsync(ByVal UserId As String, ByVal XmlIn As String) As System.Threading.Tasks.Task(Of System.IO.Stream)
        
        <System.ServiceModel.OperationContractAttribute(Action:="SetupAdd", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/SetupAddResponse")>  _
        Function SetupAdd(ByVal UserId As String, ByVal BusinessObject As String, ByVal XmlParameters As String, ByVal XmlIn As String) As System.IO.Stream
        
        <System.ServiceModel.OperationContractAttribute(Action:="SetupAdd", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/SetupAddResponse")>  _
        Function SetupAddAsync(ByVal UserId As String, ByVal BusinessObject As String, ByVal XmlParameters As String, ByVal XmlIn As String) As System.Threading.Tasks.Task(Of System.IO.Stream)
        
        <System.ServiceModel.OperationContractAttribute(Action:="SetupDelete", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/SetupDeleteResponse")>  _
        Function SetupDelete(ByVal UserId As String, ByVal BusinessObject As String, ByVal XmlParameters As String, ByVal XmlIn As String) As System.IO.Stream
        
        <System.ServiceModel.OperationContractAttribute(Action:="SetupDelete", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/SetupDeleteResponse")>  _
        Function SetupDeleteAsync(ByVal UserId As String, ByVal BusinessObject As String, ByVal XmlParameters As String, ByVal XmlIn As String) As System.Threading.Tasks.Task(Of System.IO.Stream)
        
        <System.ServiceModel.OperationContractAttribute(Action:="SetupUpdate", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/SetupUpdateResponse")>  _
        Function SetupUpdate(ByVal UserId As String, ByVal BusinessObject As String, ByVal XmlParameters As String, ByVal XmlIn As String) As System.IO.Stream
        
        <System.ServiceModel.OperationContractAttribute(Action:="SetupUpdate", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/SetupUpdateResponse")>  _
        Function SetupUpdateAsync(ByVal UserId As String, ByVal BusinessObject As String, ByVal XmlParameters As String, ByVal XmlIn As String) As System.Threading.Tasks.Task(Of System.IO.Stream)
        
        <System.ServiceModel.OperationContractAttribute(Action:="TransactionBuild", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/TransactionBuildResponse")>  _
        Function TransactionBuild(ByVal UserId As String, ByVal BusinessObject As String, ByVal XmlIn As String) As System.IO.Stream
        
        <System.ServiceModel.OperationContractAttribute(Action:="TransactionBuild", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/TransactionBuildResponse")>  _
        Function TransactionBuildAsync(ByVal UserId As String, ByVal BusinessObject As String, ByVal XmlIn As String) As System.Threading.Tasks.Task(Of System.IO.Stream)
        
        <System.ServiceModel.OperationContractAttribute(Action:="TransactionPost", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/TransactionPostResponse")>  _
        Function TransactionPost(ByVal UserId As String, ByVal BusinessObject As String, ByVal XmlParameters As String, ByVal XmlIn As String) As System.IO.Stream
        
        <System.ServiceModel.OperationContractAttribute(Action:="TransactionPost", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/TransactionPostResponse")>  _
        Function TransactionPostAsync(ByVal UserId As String, ByVal BusinessObject As String, ByVal XmlParameters As String, ByVal XmlIn As String) As System.Threading.Tasks.Task(Of System.IO.Stream)
        
        <System.ServiceModel.OperationContractAttribute(Action:="CallBusinessObjectQueryStream", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/CallBusinessObjectQueryStreamResponse")>  _
        Function CallBusinessObjectQueryStream(ByVal BOName As String, ByVal XmlInstance As String, ByVal OperatorName As String, ByVal Password As String, ByVal Company As String, ByVal CompanyPassword As String, ByVal UniqueParam As String) As System.IO.Stream
        
        <System.ServiceModel.OperationContractAttribute(Action:="CallBusinessObjectQueryStream", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/CallBusinessObjectQueryStreamResponse")>  _
        Function CallBusinessObjectQueryStreamAsync(ByVal BOName As String, ByVal XmlInstance As String, ByVal OperatorName As String, ByVal Password As String, ByVal Company As String, ByVal CompanyPassword As String, ByVal UniqueParam As String) As System.Threading.Tasks.Task(Of System.IO.Stream)
        
        <System.ServiceModel.OperationContractAttribute(Action:="CallBusinessObjectQueryBinaryStream", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/CallBusinessObjectQueryBinaryStreamResp"& _ 
            "onse")>  _
        Function CallBusinessObjectQueryBinaryStream(ByVal BOName As String, ByVal XmlInstance As String, ByVal OperatorName As String, ByVal Password As String, ByVal Company As String, ByVal CompanyPassword As String, ByVal UniqueParam As String) As System.IO.Stream
        
        <System.ServiceModel.OperationContractAttribute(Action:="CallBusinessObjectQueryBinaryStream", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/CallBusinessObjectQueryBinaryStreamResp"& _ 
            "onse")>  _
        Function CallBusinessObjectQueryBinaryStreamAsync(ByVal BOName As String, ByVal XmlInstance As String, ByVal OperatorName As String, ByVal Password As String, ByVal Company As String, ByVal CompanyPassword As String, ByVal UniqueParam As String) As System.Threading.Tasks.Task(Of System.IO.Stream)
        
        <System.ServiceModel.OperationContractAttribute(Action:="GetDashboards", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/GetDashboardsResponse")>  _
        Function GetDashboards(ByVal OperatorName As String, ByVal Password As String, ByVal Company As String, ByVal CompanyPassword As String, ByVal UniqueParam As String) As System.IO.Stream
        
        <System.ServiceModel.OperationContractAttribute(Action:="GetDashboards", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/GetDashboardsResponse")>  _
        Function GetDashboardsAsync(ByVal OperatorName As String, ByVal Password As String, ByVal Company As String, ByVal CompanyPassword As String, ByVal UniqueParam As String) As System.Threading.Tasks.Task(Of System.IO.Stream)
        
        <System.ServiceModel.OperationContractAttribute(Action:="GetSwfSize", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/GetSwfSizeResponse")>  _
        Function GetSwfSize(ByVal OperatorName As String, ByVal Password As String, ByVal Company As String, ByVal CompanyPassword As String, ByVal DashboardName As String, ByVal UniqueParam As String) As System.IO.Stream
        
        <System.ServiceModel.OperationContractAttribute(Action:="GetSwfSize", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/GetSwfSizeResponse")>  _
        Function GetSwfSizeAsync(ByVal OperatorName As String, ByVal Password As String, ByVal Company As String, ByVal CompanyPassword As String, ByVal DashboardName As String, ByVal UniqueParam As String) As System.Threading.Tasks.Task(Of System.IO.Stream)
        
        <System.ServiceModel.OperationContractAttribute(Action:="QueryDashboardScriptFile", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/QueryDashboardScriptFileResponse")>  _
        Function QueryDashboardScriptFile(ByVal Dashboard As String, ByVal GadgetDir As String, ByVal OperatorName As String, ByVal Password As String, ByVal Company As String, ByVal CompanyPassword As String, ByVal UniqueParam As String) As System.IO.Stream
        
        <System.ServiceModel.OperationContractAttribute(Action:="QueryDashboardScriptFile", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/QueryDashboardScriptFileResponse")>  _
        Function QueryDashboardScriptFileAsync(ByVal Dashboard As String, ByVal GadgetDir As String, ByVal OperatorName As String, ByVal Password As String, ByVal Company As String, ByVal CompanyPassword As String, ByVal UniqueParam As String) As System.Threading.Tasks.Task(Of System.IO.Stream)
        
        <System.ServiceModel.OperationContractAttribute(Action:="GenerateCredentialKey", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/GenerateCredentialKeyResponse")>  _
        Function GenerateCredentialKey(ByVal OperatorName As String, ByVal Password As String, ByVal CompanyCode As String, ByVal CompanyPassword As String) As System.IO.Stream
        
        <System.ServiceModel.OperationContractAttribute(Action:="GenerateCredentialKey", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/GenerateCredentialKeyResponse")>  _
        Function GenerateCredentialKeyAsync(ByVal OperatorName As String, ByVal Password As String, ByVal CompanyCode As String, ByVal CompanyPassword As String) As System.Threading.Tasks.Task(Of System.IO.Stream)
        
        <System.ServiceModel.OperationContractAttribute(Action:="SearchSYSPRO", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/SearchSYSPROResponse")>  _
        Function SearchSYSPRO(ByVal SearchParm As String, ByVal CallerId As String, ByVal ReturnXml As String) As System.IO.Stream
        
        <System.ServiceModel.OperationContractAttribute(Action:="SearchSYSPRO", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/SearchSYSPROResponse")>  _
        Function SearchSYSPROAsync(ByVal SearchParm As String, ByVal CallerId As String, ByVal ReturnXml As String) As System.Threading.Tasks.Task(Of System.IO.Stream)
        
        <System.ServiceModel.OperationContractAttribute(Action:="StockCodeXml", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/StockCodeXmlResponse")>  _
        Function StockCodeXml(ByVal StockCode As String) As System.IO.Stream
        
        <System.ServiceModel.OperationContractAttribute(Action:="StockCodeXml", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/StockCodeXmlResponse")>  _
        Function StockCodeXmlAsync(ByVal StockCode As String) As System.Threading.Tasks.Task(Of System.IO.Stream)
        
        <System.ServiceModel.OperationContractAttribute(Action:="StockCodeImage", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/StockCodeImageResponse")>  _
        Function StockCodeImage(ByVal StockCode As String) As System.IO.Stream
        
        <System.ServiceModel.OperationContractAttribute(Action:="StockCodeImage", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/StockCodeImageResponse")>  _
        Function StockCodeImageAsync(ByVal StockCode As String) As System.Threading.Tasks.Task(Of System.IO.Stream)
        
        <System.ServiceModel.OperationContractAttribute(Action:="CMSImage", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/CMSImageResponse")>  _
        Function CMSImage(ByVal ContactName As String) As System.IO.Stream
        
        <System.ServiceModel.OperationContractAttribute(Action:="CMSImage", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/CMSImageResponse")>  _
        Function CMSImageAsync(ByVal ContactName As String) As System.Threading.Tasks.Task(Of System.IO.Stream)
        
        <System.ServiceModel.OperationContractAttribute(Action:="ProvideMainFile", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/ProvideMainFileResponse")>  _
        Function ProvideMainFile(ByVal Filename As String, ByVal folder As String) As System.IO.Stream
        
        <System.ServiceModel.OperationContractAttribute(Action:="ProvideMainFile", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/ProvideMainFileResponse")>  _
        Function ProvideMainFileAsync(ByVal Filename As String, ByVal folder As String) As System.Threading.Tasks.Task(Of System.IO.Stream)
        
        <System.ServiceModel.OperationContractAttribute(Action:="ProvideImageFile", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/ProvideImageFileResponse")>  _
        Function ProvideImageFile(ByVal Filename As String) As System.IO.Stream
        
        <System.ServiceModel.OperationContractAttribute(Action:="ProvideImageFile", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/ProvideImageFileResponse")>  _
        Function ProvideImageFileAsync(ByVal Filename As String) As System.Threading.Tasks.Task(Of System.IO.Stream)
        
        <System.ServiceModel.OperationContractAttribute(Action:="SearchCustomerData", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/SearchCustomerDataResponse")>  _
        Function SearchCustomerData(ByVal Customer As String) As System.IO.Stream
        
        <System.ServiceModel.OperationContractAttribute(Action:="SearchCustomerData", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/SearchCustomerDataResponse")>  _
        Function SearchCustomerDataAsync(ByVal Customer As String) As System.Threading.Tasks.Task(Of System.IO.Stream)
        
        <System.ServiceModel.OperationContractAttribute(Action:="SearchSupplierData", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/SearchSupplierDataResponse")>  _
        Function SearchSupplierData(ByVal Supplier As String) As System.IO.Stream
        
        <System.ServiceModel.OperationContractAttribute(Action:="SearchSupplierData", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/SearchSupplierDataResponse")>  _
        Function SearchSupplierDataAsync(ByVal Supplier As String) As System.Threading.Tasks.Task(Of System.IO.Stream)
        
        <System.ServiceModel.OperationContractAttribute(Action:="SearchContactData", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/SearchContactDataResponse")>  _
        Function SearchContactData(ByVal Contact As String) As System.IO.Stream
        
        <System.ServiceModel.OperationContractAttribute(Action:="SearchContactData", ReplyAction:="http://SYSPROWcfService/ISYSPROWcfService/SearchContactDataResponse")>  _
        Function SearchContactDataAsync(ByVal Contact As String) As System.Threading.Tasks.Task(Of System.IO.Stream)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ISYSPROWcfServiceChannel
        Inherits SysproWCF.ISYSPROWcfService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class SYSPROWcfServiceClient
        Inherits System.ServiceModel.ClientBase(Of SysproWCF.ISYSPROWcfService)
        Implements SysproWCF.ISYSPROWcfService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GetLogonProfile(ByVal UserId As String) As System.IO.Stream Implements SysproWCF.ISYSPROWcfService.GetLogonProfile
            Return MyBase.Channel.GetLogonProfile(UserId)
        End Function
        
        Public Function GetLogonProfileAsync(ByVal UserId As String) As System.Threading.Tasks.Task(Of System.IO.Stream) Implements SysproWCF.ISYSPROWcfService.GetLogonProfileAsync
            Return MyBase.Channel.GetLogonProfileAsync(UserId)
        End Function
        
        Public Function Run(ByVal UserId As String, ByVal BusinessObject As String, ByVal Parameter As String) As System.IO.Stream Implements SysproWCF.ISYSPROWcfService.Run
            Return MyBase.Channel.Run(UserId, BusinessObject, Parameter)
        End Function
        
        Public Function RunAsync(ByVal UserId As String, ByVal BusinessObject As String, ByVal Parameter As String) As System.Threading.Tasks.Task(Of System.IO.Stream) Implements SysproWCF.ISYSPROWcfService.RunAsync
            Return MyBase.Channel.RunAsync(UserId, BusinessObject, Parameter)
        End Function
        
        Public Function QueryQueryW(ByVal UserId As String, ByVal BusinessObject As String, ByVal XmlIn As String) As Byte() Implements SysproWCF.ISYSPROWcfService.QueryQueryW
            Return MyBase.Channel.QueryQueryW(UserId, BusinessObject, XmlIn)
        End Function
        
        Public Function QueryQueryWAsync(ByVal UserId As String, ByVal BusinessObject As String, ByVal XmlIn As String) As System.Threading.Tasks.Task(Of Byte()) Implements SysproWCF.ISYSPROWcfService.QueryQueryWAsync
            Return MyBase.Channel.QueryQueryWAsync(UserId, BusinessObject, XmlIn)
        End Function
        
        Public Function TransactionPostW(ByVal UserId As String, ByVal BusinessObject As String, ByVal XmlParameters As String, ByVal XmlIn As String) As Byte() Implements SysproWCF.ISYSPROWcfService.TransactionPostW
            Return MyBase.Channel.TransactionPostW(UserId, BusinessObject, XmlParameters, XmlIn)
        End Function
        
        Public Function TransactionPostWAsync(ByVal UserId As String, ByVal BusinessObject As String, ByVal XmlParameters As String, ByVal XmlIn As String) As System.Threading.Tasks.Task(Of Byte()) Implements SysproWCF.ISYSPROWcfService.TransactionPostWAsync
            Return MyBase.Channel.TransactionPostWAsync(UserId, BusinessObject, XmlParameters, XmlIn)
        End Function
        
        Public Function GetImage(ByVal Filename As String) As System.IO.Stream Implements SysproWCF.ISYSPROWcfService.GetImage
            Return MyBase.Channel.GetImage(Filename)
        End Function
        
        Public Function GetImageAsync(ByVal Filename As String) As System.Threading.Tasks.Task(Of System.IO.Stream) Implements SysproWCF.ISYSPROWcfService.GetImageAsync
            Return MyBase.Channel.GetImageAsync(Filename)
        End Function
        
        Public Function GetSystemInformation() As System.IO.Stream Implements SysproWCF.ISYSPROWcfService.GetSystemInformation
            Return MyBase.Channel.GetSystemInformation
        End Function
        
        Public Function GetSystemInformationAsync() As System.Threading.Tasks.Task(Of System.IO.Stream) Implements SysproWCF.ISYSPROWcfService.GetSystemInformationAsync
            Return MyBase.Channel.GetSystemInformationAsync
        End Function
        
        Public Function GetVersion() As System.IO.Stream Implements SysproWCF.ISYSPROWcfService.GetVersion
            Return MyBase.Channel.GetVersion
        End Function
        
        Public Function GetVersionAsync() As System.Threading.Tasks.Task(Of System.IO.Stream) Implements SysproWCF.ISYSPROWcfService.GetVersionAsync
            Return MyBase.Channel.GetVersionAsync
        End Function
        
        Public Function CallGC() As System.IO.Stream Implements SysproWCF.ISYSPROWcfService.CallGC
            Return MyBase.Channel.CallGC
        End Function
        
        Public Function CallGCAsync() As System.Threading.Tasks.Task(Of System.IO.Stream) Implements SysproWCF.ISYSPROWcfService.CallGCAsync
            Return MyBase.Channel.CallGCAsync
        End Function
        
        Public Function Encrypt(ByVal InputString As String) As System.IO.Stream Implements SysproWCF.ISYSPROWcfService.Encrypt
            Return MyBase.Channel.Encrypt(InputString)
        End Function
        
        Public Function EncryptAsync(ByVal InputString As String) As System.Threading.Tasks.Task(Of System.IO.Stream) Implements SysproWCF.ISYSPROWcfService.EncryptAsync
            Return MyBase.Channel.EncryptAsync(InputString)
        End Function
        
        Public Function GetSYSPROMedia(ByVal MultimediaFlag As String, ByVal ObjectType As String, ByVal KeyField As String, ByVal EnetGuid As String) As System.IO.Stream Implements SysproWCF.ISYSPROWcfService.GetSYSPROMedia
            Return MyBase.Channel.GetSYSPROMedia(MultimediaFlag, ObjectType, KeyField, EnetGuid)
        End Function
        
        Public Function GetSYSPROMediaAsync(ByVal MultimediaFlag As String, ByVal ObjectType As String, ByVal KeyField As String, ByVal EnetGuid As String) As System.Threading.Tasks.Task(Of System.IO.Stream) Implements SysproWCF.ISYSPROWcfService.GetSYSPROMediaAsync
            Return MyBase.Channel.GetSYSPROMediaAsync(MultimediaFlag, ObjectType, KeyField, EnetGuid)
        End Function
        
        Public Function GetSYSPROImageThumbnail(ByVal MultimediaFlag As String, ByVal ObjectType As String, ByVal KeyField As String, ByVal EnetGuid As String, ByVal Width As Integer, ByVal Height As Integer) As System.IO.Stream Implements SysproWCF.ISYSPROWcfService.GetSYSPROImageThumbnail
            Return MyBase.Channel.GetSYSPROImageThumbnail(MultimediaFlag, ObjectType, KeyField, EnetGuid, Width, Height)
        End Function
        
        Public Function GetSYSPROImageThumbnailAsync(ByVal MultimediaFlag As String, ByVal ObjectType As String, ByVal KeyField As String, ByVal EnetGuid As String, ByVal Width As Integer, ByVal Height As Integer) As System.Threading.Tasks.Task(Of System.IO.Stream) Implements SysproWCF.ISYSPROWcfService.GetSYSPROImageThumbnailAsync
            Return MyBase.Channel.GetSYSPROImageThumbnailAsync(MultimediaFlag, ObjectType, KeyField, EnetGuid, Width, Height)
        End Function
        
        Public Function Logon(ByVal [Operator] As String, ByVal OperatorPassword As String, ByVal CompanyId As String, ByVal CompanyPassword As String, ByVal LanguageCode As String, ByVal LogLevel As String, ByVal EncoreInstance As String, ByVal XmlIn As String) As System.IO.Stream Implements SysproWCF.ISYSPROWcfService.Logon
            Return MyBase.Channel.Logon([Operator], OperatorPassword, CompanyId, CompanyPassword, LanguageCode, LogLevel, EncoreInstance, XmlIn)
        End Function
        
        Public Function LogonAsync(ByVal [Operator] As String, ByVal OperatorPassword As String, ByVal CompanyId As String, ByVal CompanyPassword As String, ByVal LanguageCode As String, ByVal LogLevel As String, ByVal EncoreInstance As String, ByVal XmlIn As String) As System.Threading.Tasks.Task(Of System.IO.Stream) Implements SysproWCF.ISYSPROWcfService.LogonAsync
            Return MyBase.Channel.LogonAsync([Operator], OperatorPassword, CompanyId, CompanyPassword, LanguageCode, LogLevel, EncoreInstance, XmlIn)
        End Function
        
        Public Function Logoff(ByVal UserId As String) As System.IO.Stream Implements SysproWCF.ISYSPROWcfService.Logoff
            Return MyBase.Channel.Logoff(UserId)
        End Function
        
        Public Function LogoffAsync(ByVal UserId As String) As System.Threading.Tasks.Task(Of System.IO.Stream) Implements SysproWCF.ISYSPROWcfService.LogoffAsync
            Return MyBase.Channel.LogoffAsync(UserId)
        End Function
        
        Public Function QueryBrowse(ByVal UserId As String, ByVal XmlIn As String) As System.IO.Stream Implements SysproWCF.ISYSPROWcfService.QueryBrowse
            Return MyBase.Channel.QueryBrowse(UserId, XmlIn)
        End Function
        
        Public Function QueryBrowseAsync(ByVal UserId As String, ByVal XmlIn As String) As System.Threading.Tasks.Task(Of System.IO.Stream) Implements SysproWCF.ISYSPROWcfService.QueryBrowseAsync
            Return MyBase.Channel.QueryBrowseAsync(UserId, XmlIn)
        End Function
        
        Public Function QueryFetch(ByVal UserId As String, ByVal XmlIn As String) As System.IO.Stream Implements SysproWCF.ISYSPROWcfService.QueryFetch
            Return MyBase.Channel.QueryFetch(UserId, XmlIn)
        End Function
        
        Public Function QueryFetchAsync(ByVal UserId As String, ByVal XmlIn As String) As System.Threading.Tasks.Task(Of System.IO.Stream) Implements SysproWCF.ISYSPROWcfService.QueryFetchAsync
            Return MyBase.Channel.QueryFetchAsync(UserId, XmlIn)
        End Function
        
        Public Function QueryQuery(ByVal UserId As String, ByVal BusinessObject As String, ByVal XmlIn As String) As System.IO.Stream Implements SysproWCF.ISYSPROWcfService.QueryQuery
            Return MyBase.Channel.QueryQuery(UserId, BusinessObject, XmlIn)
        End Function
        
        Public Function QueryQueryAsync(ByVal UserId As String, ByVal BusinessObject As String, ByVal XmlIn As String) As System.Threading.Tasks.Task(Of System.IO.Stream) Implements SysproWCF.ISYSPROWcfService.QueryQueryAsync
            Return MyBase.Channel.QueryQueryAsync(UserId, BusinessObject, XmlIn)
        End Function
        
        Public Function NextKey(ByVal UserId As String, ByVal XmlIn As String) As System.IO.Stream Implements SysproWCF.ISYSPROWcfService.NextKey
            Return MyBase.Channel.NextKey(UserId, XmlIn)
        End Function
        
        Public Function NextKeyAsync(ByVal UserId As String, ByVal XmlIn As String) As System.Threading.Tasks.Task(Of System.IO.Stream) Implements SysproWCF.ISYSPROWcfService.NextKeyAsync
            Return MyBase.Channel.NextKeyAsync(UserId, XmlIn)
        End Function
        
        Public Function PreviousKey(ByVal UserId As String, ByVal XmlIn As String) As System.IO.Stream Implements SysproWCF.ISYSPROWcfService.PreviousKey
            Return MyBase.Channel.PreviousKey(UserId, XmlIn)
        End Function
        
        Public Function PreviousKeyAsync(ByVal UserId As String, ByVal XmlIn As String) As System.Threading.Tasks.Task(Of System.IO.Stream) Implements SysproWCF.ISYSPROWcfService.PreviousKeyAsync
            Return MyBase.Channel.PreviousKeyAsync(UserId, XmlIn)
        End Function
        
        Public Function SetupAdd(ByVal UserId As String, ByVal BusinessObject As String, ByVal XmlParameters As String, ByVal XmlIn As String) As System.IO.Stream Implements SysproWCF.ISYSPROWcfService.SetupAdd
            Return MyBase.Channel.SetupAdd(UserId, BusinessObject, XmlParameters, XmlIn)
        End Function
        
        Public Function SetupAddAsync(ByVal UserId As String, ByVal BusinessObject As String, ByVal XmlParameters As String, ByVal XmlIn As String) As System.Threading.Tasks.Task(Of System.IO.Stream) Implements SysproWCF.ISYSPROWcfService.SetupAddAsync
            Return MyBase.Channel.SetupAddAsync(UserId, BusinessObject, XmlParameters, XmlIn)
        End Function
        
        Public Function SetupDelete(ByVal UserId As String, ByVal BusinessObject As String, ByVal XmlParameters As String, ByVal XmlIn As String) As System.IO.Stream Implements SysproWCF.ISYSPROWcfService.SetupDelete
            Return MyBase.Channel.SetupDelete(UserId, BusinessObject, XmlParameters, XmlIn)
        End Function
        
        Public Function SetupDeleteAsync(ByVal UserId As String, ByVal BusinessObject As String, ByVal XmlParameters As String, ByVal XmlIn As String) As System.Threading.Tasks.Task(Of System.IO.Stream) Implements SysproWCF.ISYSPROWcfService.SetupDeleteAsync
            Return MyBase.Channel.SetupDeleteAsync(UserId, BusinessObject, XmlParameters, XmlIn)
        End Function
        
        Public Function SetupUpdate(ByVal UserId As String, ByVal BusinessObject As String, ByVal XmlParameters As String, ByVal XmlIn As String) As System.IO.Stream Implements SysproWCF.ISYSPROWcfService.SetupUpdate
            Return MyBase.Channel.SetupUpdate(UserId, BusinessObject, XmlParameters, XmlIn)
        End Function
        
        Public Function SetupUpdateAsync(ByVal UserId As String, ByVal BusinessObject As String, ByVal XmlParameters As String, ByVal XmlIn As String) As System.Threading.Tasks.Task(Of System.IO.Stream) Implements SysproWCF.ISYSPROWcfService.SetupUpdateAsync
            Return MyBase.Channel.SetupUpdateAsync(UserId, BusinessObject, XmlParameters, XmlIn)
        End Function
        
        Public Function TransactionBuild(ByVal UserId As String, ByVal BusinessObject As String, ByVal XmlIn As String) As System.IO.Stream Implements SysproWCF.ISYSPROWcfService.TransactionBuild
            Return MyBase.Channel.TransactionBuild(UserId, BusinessObject, XmlIn)
        End Function
        
        Public Function TransactionBuildAsync(ByVal UserId As String, ByVal BusinessObject As String, ByVal XmlIn As String) As System.Threading.Tasks.Task(Of System.IO.Stream) Implements SysproWCF.ISYSPROWcfService.TransactionBuildAsync
            Return MyBase.Channel.TransactionBuildAsync(UserId, BusinessObject, XmlIn)
        End Function
        
        Public Function TransactionPost(ByVal UserId As String, ByVal BusinessObject As String, ByVal XmlParameters As String, ByVal XmlIn As String) As System.IO.Stream Implements SysproWCF.ISYSPROWcfService.TransactionPost
            Return MyBase.Channel.TransactionPost(UserId, BusinessObject, XmlParameters, XmlIn)
        End Function
        
        Public Function TransactionPostAsync(ByVal UserId As String, ByVal BusinessObject As String, ByVal XmlParameters As String, ByVal XmlIn As String) As System.Threading.Tasks.Task(Of System.IO.Stream) Implements SysproWCF.ISYSPROWcfService.TransactionPostAsync
            Return MyBase.Channel.TransactionPostAsync(UserId, BusinessObject, XmlParameters, XmlIn)
        End Function
        
        Public Function CallBusinessObjectQueryStream(ByVal BOName As String, ByVal XmlInstance As String, ByVal OperatorName As String, ByVal Password As String, ByVal Company As String, ByVal CompanyPassword As String, ByVal UniqueParam As String) As System.IO.Stream Implements SysproWCF.ISYSPROWcfService.CallBusinessObjectQueryStream
            Return MyBase.Channel.CallBusinessObjectQueryStream(BOName, XmlInstance, OperatorName, Password, Company, CompanyPassword, UniqueParam)
        End Function
        
        Public Function CallBusinessObjectQueryStreamAsync(ByVal BOName As String, ByVal XmlInstance As String, ByVal OperatorName As String, ByVal Password As String, ByVal Company As String, ByVal CompanyPassword As String, ByVal UniqueParam As String) As System.Threading.Tasks.Task(Of System.IO.Stream) Implements SysproWCF.ISYSPROWcfService.CallBusinessObjectQueryStreamAsync
            Return MyBase.Channel.CallBusinessObjectQueryStreamAsync(BOName, XmlInstance, OperatorName, Password, Company, CompanyPassword, UniqueParam)
        End Function
        
        Public Function CallBusinessObjectQueryBinaryStream(ByVal BOName As String, ByVal XmlInstance As String, ByVal OperatorName As String, ByVal Password As String, ByVal Company As String, ByVal CompanyPassword As String, ByVal UniqueParam As String) As System.IO.Stream Implements SysproWCF.ISYSPROWcfService.CallBusinessObjectQueryBinaryStream
            Return MyBase.Channel.CallBusinessObjectQueryBinaryStream(BOName, XmlInstance, OperatorName, Password, Company, CompanyPassword, UniqueParam)
        End Function
        
        Public Function CallBusinessObjectQueryBinaryStreamAsync(ByVal BOName As String, ByVal XmlInstance As String, ByVal OperatorName As String, ByVal Password As String, ByVal Company As String, ByVal CompanyPassword As String, ByVal UniqueParam As String) As System.Threading.Tasks.Task(Of System.IO.Stream) Implements SysproWCF.ISYSPROWcfService.CallBusinessObjectQueryBinaryStreamAsync
            Return MyBase.Channel.CallBusinessObjectQueryBinaryStreamAsync(BOName, XmlInstance, OperatorName, Password, Company, CompanyPassword, UniqueParam)
        End Function
        
        Public Function GetDashboards(ByVal OperatorName As String, ByVal Password As String, ByVal Company As String, ByVal CompanyPassword As String, ByVal UniqueParam As String) As System.IO.Stream Implements SysproWCF.ISYSPROWcfService.GetDashboards
            Return MyBase.Channel.GetDashboards(OperatorName, Password, Company, CompanyPassword, UniqueParam)
        End Function
        
        Public Function GetDashboardsAsync(ByVal OperatorName As String, ByVal Password As String, ByVal Company As String, ByVal CompanyPassword As String, ByVal UniqueParam As String) As System.Threading.Tasks.Task(Of System.IO.Stream) Implements SysproWCF.ISYSPROWcfService.GetDashboardsAsync
            Return MyBase.Channel.GetDashboardsAsync(OperatorName, Password, Company, CompanyPassword, UniqueParam)
        End Function
        
        Public Function GetSwfSize(ByVal OperatorName As String, ByVal Password As String, ByVal Company As String, ByVal CompanyPassword As String, ByVal DashboardName As String, ByVal UniqueParam As String) As System.IO.Stream Implements SysproWCF.ISYSPROWcfService.GetSwfSize
            Return MyBase.Channel.GetSwfSize(OperatorName, Password, Company, CompanyPassword, DashboardName, UniqueParam)
        End Function
        
        Public Function GetSwfSizeAsync(ByVal OperatorName As String, ByVal Password As String, ByVal Company As String, ByVal CompanyPassword As String, ByVal DashboardName As String, ByVal UniqueParam As String) As System.Threading.Tasks.Task(Of System.IO.Stream) Implements SysproWCF.ISYSPROWcfService.GetSwfSizeAsync
            Return MyBase.Channel.GetSwfSizeAsync(OperatorName, Password, Company, CompanyPassword, DashboardName, UniqueParam)
        End Function
        
        Public Function QueryDashboardScriptFile(ByVal Dashboard As String, ByVal GadgetDir As String, ByVal OperatorName As String, ByVal Password As String, ByVal Company As String, ByVal CompanyPassword As String, ByVal UniqueParam As String) As System.IO.Stream Implements SysproWCF.ISYSPROWcfService.QueryDashboardScriptFile
            Return MyBase.Channel.QueryDashboardScriptFile(Dashboard, GadgetDir, OperatorName, Password, Company, CompanyPassword, UniqueParam)
        End Function
        
        Public Function QueryDashboardScriptFileAsync(ByVal Dashboard As String, ByVal GadgetDir As String, ByVal OperatorName As String, ByVal Password As String, ByVal Company As String, ByVal CompanyPassword As String, ByVal UniqueParam As String) As System.Threading.Tasks.Task(Of System.IO.Stream) Implements SysproWCF.ISYSPROWcfService.QueryDashboardScriptFileAsync
            Return MyBase.Channel.QueryDashboardScriptFileAsync(Dashboard, GadgetDir, OperatorName, Password, Company, CompanyPassword, UniqueParam)
        End Function
        
        Public Function GenerateCredentialKey(ByVal OperatorName As String, ByVal Password As String, ByVal CompanyCode As String, ByVal CompanyPassword As String) As System.IO.Stream Implements SysproWCF.ISYSPROWcfService.GenerateCredentialKey
            Return MyBase.Channel.GenerateCredentialKey(OperatorName, Password, CompanyCode, CompanyPassword)
        End Function
        
        Public Function GenerateCredentialKeyAsync(ByVal OperatorName As String, ByVal Password As String, ByVal CompanyCode As String, ByVal CompanyPassword As String) As System.Threading.Tasks.Task(Of System.IO.Stream) Implements SysproWCF.ISYSPROWcfService.GenerateCredentialKeyAsync
            Return MyBase.Channel.GenerateCredentialKeyAsync(OperatorName, Password, CompanyCode, CompanyPassword)
        End Function
        
        Public Function SearchSYSPRO(ByVal SearchParm As String, ByVal CallerId As String, ByVal ReturnXml As String) As System.IO.Stream Implements SysproWCF.ISYSPROWcfService.SearchSYSPRO
            Return MyBase.Channel.SearchSYSPRO(SearchParm, CallerId, ReturnXml)
        End Function
        
        Public Function SearchSYSPROAsync(ByVal SearchParm As String, ByVal CallerId As String, ByVal ReturnXml As String) As System.Threading.Tasks.Task(Of System.IO.Stream) Implements SysproWCF.ISYSPROWcfService.SearchSYSPROAsync
            Return MyBase.Channel.SearchSYSPROAsync(SearchParm, CallerId, ReturnXml)
        End Function
        
        Public Function StockCodeXml(ByVal StockCode As String) As System.IO.Stream Implements SysproWCF.ISYSPROWcfService.StockCodeXml
            Return MyBase.Channel.StockCodeXml(StockCode)
        End Function
        
        Public Function StockCodeXmlAsync(ByVal StockCode As String) As System.Threading.Tasks.Task(Of System.IO.Stream) Implements SysproWCF.ISYSPROWcfService.StockCodeXmlAsync
            Return MyBase.Channel.StockCodeXmlAsync(StockCode)
        End Function
        
        Public Function StockCodeImage(ByVal StockCode As String) As System.IO.Stream Implements SysproWCF.ISYSPROWcfService.StockCodeImage
            Return MyBase.Channel.StockCodeImage(StockCode)
        End Function
        
        Public Function StockCodeImageAsync(ByVal StockCode As String) As System.Threading.Tasks.Task(Of System.IO.Stream) Implements SysproWCF.ISYSPROWcfService.StockCodeImageAsync
            Return MyBase.Channel.StockCodeImageAsync(StockCode)
        End Function
        
        Public Function CMSImage(ByVal ContactName As String) As System.IO.Stream Implements SysproWCF.ISYSPROWcfService.CMSImage
            Return MyBase.Channel.CMSImage(ContactName)
        End Function
        
        Public Function CMSImageAsync(ByVal ContactName As String) As System.Threading.Tasks.Task(Of System.IO.Stream) Implements SysproWCF.ISYSPROWcfService.CMSImageAsync
            Return MyBase.Channel.CMSImageAsync(ContactName)
        End Function
        
        Public Function ProvideMainFile(ByVal Filename As String, ByVal folder As String) As System.IO.Stream Implements SysproWCF.ISYSPROWcfService.ProvideMainFile
            Return MyBase.Channel.ProvideMainFile(Filename, folder)
        End Function
        
        Public Function ProvideMainFileAsync(ByVal Filename As String, ByVal folder As String) As System.Threading.Tasks.Task(Of System.IO.Stream) Implements SysproWCF.ISYSPROWcfService.ProvideMainFileAsync
            Return MyBase.Channel.ProvideMainFileAsync(Filename, folder)
        End Function
        
        Public Function ProvideImageFile(ByVal Filename As String) As System.IO.Stream Implements SysproWCF.ISYSPROWcfService.ProvideImageFile
            Return MyBase.Channel.ProvideImageFile(Filename)
        End Function
        
        Public Function ProvideImageFileAsync(ByVal Filename As String) As System.Threading.Tasks.Task(Of System.IO.Stream) Implements SysproWCF.ISYSPROWcfService.ProvideImageFileAsync
            Return MyBase.Channel.ProvideImageFileAsync(Filename)
        End Function
        
        Public Function SearchCustomerData(ByVal Customer As String) As System.IO.Stream Implements SysproWCF.ISYSPROWcfService.SearchCustomerData
            Return MyBase.Channel.SearchCustomerData(Customer)
        End Function
        
        Public Function SearchCustomerDataAsync(ByVal Customer As String) As System.Threading.Tasks.Task(Of System.IO.Stream) Implements SysproWCF.ISYSPROWcfService.SearchCustomerDataAsync
            Return MyBase.Channel.SearchCustomerDataAsync(Customer)
        End Function
        
        Public Function SearchSupplierData(ByVal Supplier As String) As System.IO.Stream Implements SysproWCF.ISYSPROWcfService.SearchSupplierData
            Return MyBase.Channel.SearchSupplierData(Supplier)
        End Function
        
        Public Function SearchSupplierDataAsync(ByVal Supplier As String) As System.Threading.Tasks.Task(Of System.IO.Stream) Implements SysproWCF.ISYSPROWcfService.SearchSupplierDataAsync
            Return MyBase.Channel.SearchSupplierDataAsync(Supplier)
        End Function
        
        Public Function SearchContactData(ByVal Contact As String) As System.IO.Stream Implements SysproWCF.ISYSPROWcfService.SearchContactData
            Return MyBase.Channel.SearchContactData(Contact)
        End Function
        
        Public Function SearchContactDataAsync(ByVal Contact As String) As System.Threading.Tasks.Task(Of System.IO.Stream) Implements SysproWCF.ISYSPROWcfService.SearchContactDataAsync
            Return MyBase.Channel.SearchContactDataAsync(Contact)
        End Function
    End Class
End Namespace
